import Head from "next/head";
import styles from "../styles/Home.module.css";
import Sidebar from "../components/Sidebar";
import {
	VStack,
	HStack,
	Grid,
	Heading,
	Avatar,
	Text,
	Image,
} from "@chakra-ui/react";
import { ApolloContext } from "../context/ApolloContext";
import { useContext, useEffect, useState } from "react";

export default function Home() {
	const [recommendedProfiles, setRecommendedProfiles] = useState([]);
	const { getRecommendedProfiles } = useContext(ApolloContext);
	useEffect(() => {
		(async () => {
			let response = await getRecommendedProfiles();
			setRecommendedProfiles(response.data.recommendedProfiles);
		})();
	}, []);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<VStack py="75px" height="100vh" spacing="0">
				<Grid templateColumns="1fr 4fr" width="100%" height="100%">
					<Sidebar recommendedProfiles={recommendedProfiles} />
					<VStack padding={5} alignItems="flex-start">
						<Heading>Discover</Heading>
						<Grid gridGap={4} templateColumns="repeat(4, 1fr)">
							<VStack>
								<Image
									layout="fill"
									src="https://static-cdn.jtvnw.net/previews-ttv/live_user_prod-440x248.jpg"
								/>
								<HStack
									justifyContent="flex-start"
									width="100%"
								>
									<Avatar src="https://bit.ly/dan-abramov" />
									<VStack
										width="100%"
										alignItems="flex-start"
										spacing={0}
									>
										<Text>Title</Text>
										<Text>username</Text>
									</VStack>
								</HStack>
							</VStack>
							<VStack>
								<Image
									layout="fill"
									src="https://static-cdn.jtvnw.net/previews-ttv/live_user_prod-440x248.jpg"
								/>
								<HStack
									justifyContent="flex-start"
									width="100%"
								>
									<Avatar src="https://bit.ly/dan-abramov" />
									<VStack
										width="100%"
										alignItems="flex-start"
										spacing={0}
									>
										<Text>Title</Text>
										<Text>username</Text>
									</VStack>
								</HStack>
							</VStack>
							<VStack>
								<Image
									layout="fill"
									src="https://static-cdn.jtvnw.net/previews-ttv/live_user_prod-440x248.jpg"
								/>
								<HStack
									justifyContent="flex-start"
									width="100%"
								>
									<Avatar src="https://bit.ly/dan-abramov" />
									<VStack
										width="100%"
										alignItems="flex-start"
										spacing={0}
									>
										<Text>Title</Text>
										<Text>username</Text>
									</VStack>
								</HStack>
							</VStack>
							<VStack>
								<Image
									layout="fill"
									src="https://static-cdn.jtvnw.net/previews-ttv/live_user_prod-440x248.jpg"
								/>
								<HStack
									justifyContent="flex-start"
									width="100%"
								>
									<Avatar src="https://bit.ly/dan-abramov" />
									<VStack
										width="100%"
										alignItems="flex-start"
										spacing={0}
									>
										<Text>Title</Text>
										<Text>username</Text>
									</VStack>
								</HStack>
							</VStack>
							<VStack>
								<Image
									layout="fill"
									src="https://static-cdn.jtvnw.net/previews-ttv/live_user_prod-440x248.jpg"
								/>
								<HStack
									justifyContent="flex-start"
									width="100%"
								>
									<Avatar src="https://bit.ly/dan-abramov" />
									<VStack
										width="100%"
										alignItems="flex-start"
										spacing={0}
									>
										<Text>Title</Text>
										<Text>username</Text>
									</VStack>
								</HStack>
							</VStack>
						</Grid>
					</VStack>
				</Grid>
			</VStack>
		</div>
	);
}
